export enum VideoHumanType {
  raw = 'raw',
  edited = 'edited',
}

export interface IFileOriginalProps {
  id?: string;
  path: string;
  name: string;
  size: number;
  last_modified: number;
  type: string;
  duration?: number | null;
}

export interface IVideoFFProbeData {
  format: {
    size: string;
    tags: {
      major_brand: string;
      creation_time: string;
      minor_version: string;
      compatible_brands: string;
    };
    bit_rate: string;
    duration: string;
    filename: string;
    nb_streams: number;
    start_time: string;
    format_name: string;
    nb_programs: number;
    probe_score: number;
    format_long_name: string;
  };
  streams: [
    {
      refs: 1;
      tags: {
        language: 'und';
        vendor_id: '[0][0][0][0]';
        handler_name: 'ISO Media file produced by Google Inc. Created on: 11/28/2021.';
        creation_time: '2021-11-28T15:11:37.000000Z';
      };
      index: 0;
      level: 31;
      width: number;
      height: number;
      is_avc: 'true';
      pix_fmt: 'yuv420p';
      profile: 'Main';
      bit_rate: '689879';
      duration: '524.466667';
      codec_tag: '0x31637661';
      nb_frames: '15734';
      start_pts: 0;
      time_base: '1/15360';
      codec_name: 'h264';
      codec_type: 'video';
      start_time: '0.000000';
      coded_width: 1280;
      color_range: 'tv';
      color_space: 'bt709';
      disposition: {
        dub: 0;
        forced: 0;
        lyrics: 0;
        comment: 0;
        default: 1;
        karaoke: 0;
        original: 0;
        attached_pic: 0;
        clean_effects: 0;
        visual_impaired: 0;
        hearing_impaired: 0;
        timed_thumbnails: 0;
      };
      duration_ts: 8055808;
      coded_height: 720;
      has_b_frames: 1;
      r_frame_rate: '30/1';
      avg_frame_rate: '30/1';
      color_transfer: 'bt709';
      chroma_location: 'left';
      closed_captions: 0;
      codec_long_name: 'H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10';
      color_primaries: 'bt709';
      nal_length_size: '4';
      codec_tag_string: 'avc1';
      bits_per_raw_sample: '8';
      sample_aspect_ratio: '1:1';
      display_aspect_ratio: '16:9';
    },
    {
      tags: {
        language: 'eng';
        vendor_id: '[0][0][0][0]';
        handler_name: 'ISO Media file produced by Google Inc. Created on: 11/28/2021.';
        creation_time: '2021-11-28T15:11:37.000000Z';
      };
      index: 1;
      profile: 'LC';
      bit_rate: '128005';
      channels: 2;
      duration: '524.469116';
      codec_tag: '0x6134706d';
      nb_frames: '22587';
      start_pts: 0;
      time_base: '1/44100';
      codec_name: 'aac';
      codec_type: 'audio';
      sample_fmt: 'fltp';
      start_time: '0.000000';
      disposition: {
        dub: 0;
        forced: 0;
        lyrics: 0;
        comment: 0;
        default: 1;
        karaoke: 0;
        original: 0;
        attached_pic: 0;
        clean_effects: 0;
        visual_impaired: 0;
        hearing_impaired: 0;
        timed_thumbnails: 0;
      };
      duration_ts: 23129088;
      sample_rate: '44100';
      r_frame_rate: '0/0';
      avg_frame_rate: '0/0';
      channel_layout: 'stereo';
      bits_per_sample: 0;
      codec_long_name: 'AAC (Advanced Audio Coding)';
      codec_tag_string: 'mp4a';
    },
  ];
}

export interface IVideoEncodeDefinition {
  metadata: {
    url: string;
    name: string;
    video_id: string;
    extension: string;
  };
  target_fps: number;
  resolutions: string[];
  target_path: string;
  split_seconds: number;
  resolution_bitrates: {
    '854x480': '1500k';
    '1280x720': '2500k';
    '1920x1080': '4000k';
  };
  resolution_bandwidths: {
    '854x480': 1000000;
    '1280x720': 1500000;
    '1920x1080': 2000000;
  };
}

export interface ISambaFileInfo {
  duration: number;
  bitrate: number;
  framerate: number;
  width: number;
  height: number;
  videoCodec: string;
  audioCodec: string;
  audioChannels: number;
  audioSampleRate: number;
}

export interface ISambaFile {
  id: string;
  qualifier: string;
  fileName: string | null;
  fileSize: string;
  status: string;
  postdate: number;
  mimeType: string | null;
  outputName: string;
  outputId: number;
  url: string;
  md5: string | null;
  assetId: string | null;
  assetName: string | null;
  container: string | null;
  fileInfo: ISambaFileInfo;
  fileInfoType: string;
}

export interface ISambaThumb {
  height: number;
  size: number;
  width: number;
  url: string;
  status: string;
}

export interface ISambaSubtitleFileInfo {
  captionLanguage: string;
  altLanguages: string | null;
  closedCaption: boolean;
  mediaFolderId: string | null;
  captionElementId: string | null;
  status: string | null;
  enabled: boolean;
  autoGenerated: boolean;
  generatedSrtUrl: string;
  lastModified: number | null;
}

export interface ISambaCaption {
  id: string;
  qualifier: string;
  fileName: string;
  fileSize: string;
  status: string;
  postdate: number;
  mimeType: string | null;
  outputName: string | null;
  outputId: string | null;
  url: string;
  md5: string | null;
  assetId: string | null;
  assetName: string | null;
  container: string | null;
  fileInfo: ISambaSubtitleFileInfo;
  fileInfoType: string;
}

export interface ISambaData {
  id: string;
  title: string;
  status: string;
  qualifier: string;
  fileName: string | null;
  description: string | null;
  shortDescription: string | null;
  categoryName: string;
  categoryId: number;
  postdate: number;
  lastModified: number;
  publishDate: number;
  unpublishDate: number | null;
  published: boolean;
  highlighted: boolean;
  restricted: boolean;
  secondUrl: string | null;
  numberOfViews: number;
  numberOfComments: number;
  numberOfRatings: number;
  childStatus: string;
  blocked: boolean;
  processingChange: string | null;
  tags: any[];
  files: ISambaFile[];
  thumbs: ISambaThumb[];
  genders: any[]; // Adjust type if you know what this contains
  captions: ISambaCaption[];
  libras: any | null; // Adjust type if needed
  liveChannelId: any | null; // Adjust type if needed
  blockedsSet: boolean;
  videoMigrated: string;
}
