version: '3.9'
services:
  frontend:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    image: 'admin_redaplus'
    container_name: 'admin_redaplus'
    restart: 'unless-stopped'
    volumes:
      - './:/app'
    ports:
      - '8083:8083'
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: '3G'
