name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install backend dependencies
        run: npm install

      - name: Run backend tests
        run: npm test

      - name: Build backend
        run: npm run build

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-and-test-backend

    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v3
        with:
          # Checkout do repo inteiro
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: Frontend/redaplus
        run: npm install

      - name: Build frontend
        working-directory: Frontend/redaplus
        run: npm run build
